"""
data_category_b.py — カテゴリB: 航海用刊行物マスターデータ (22件)
================================================================
日本水路部(JHO)、英国水路部(UKHO)、米国NGA、ITU無線刊行物、
及び航海実務参考書のデータ定義。
"""

from __future__ import annotations

from .constants import CAT_B, MANDATORY, RECOMMENDED


# ---------------------------------------------------------------------------
# 日本水路部 (JHO)
# ---------------------------------------------------------------------------

JHO_PUBLICATIONS: list[dict] = [
    {
        "publication_id": "JHO_CHART_CATALOG",
        "title": "Chart Catalogue (Japan Hydrographic Office)",
        "title_ja": "海図総目録",
        "category": CAT_B,
        "legal_basis": "海上保安庁法 / 水路業務法",
        "publisher": "日本水路協会",
        "current_edition": "2026年版",
        "current_edition_date": "2026-04-01",
        "update_cycle": "年1回",
        "priority": MANDATORY,
        "applicability_rules": {
            "conventions": [],
            "ship_types": [],
            "excluded_types": [],
            "gt_min": None,
            "gt_max": None,
            "navigation": [],
            "flag_state": "JPN",
            "class_society": None,
            "radio_equipment": [],
            "build_year_before": None,
            "build_year_after": None,
        },
        "reason_template": "日本旗船として海図総目録の備付義務",
    },
    {
        "publication_id": "JHO_SAILING_DIRECTIONS",
        "title": "Sailing Directions (Japan)",
        "title_ja": "水路誌",
        "category": CAT_B,
        "legal_basis": "船舶安全法 / 船舶設備規程",
        "publisher": "日本水路協会",
        "current_edition": "最新版",
        "current_edition_date": None,
        "update_cycle": "不定期改訂",
        "priority": MANDATORY,
        "applicability_rules": {
            "conventions": [],
            "ship_types": [],
            "excluded_types": [],
            "gt_min": None,
            "gt_max": None,
            "navigation": [],
            "flag_state": "JPN",
            "class_society": None,
            "radio_equipment": [],
            "build_year_before": None,
            "build_year_after": None,
        },
        "reason_template": "日本旗船として水路誌の備付義務",
    },
    {
        "publication_id": "JHO_LIST_OF_LIGHTS",
        "title": "List of Lights (Japan)",
        "title_ja": "灯台表",
        "category": CAT_B,
        "legal_basis": "船舶安全法 / 船舶設備規程",
        "publisher": "日本水路協会",
        "current_edition": "2026年版",
        "current_edition_date": "2026-01-01",
        "update_cycle": "年1回",
        "priority": MANDATORY,
        "applicability_rules": {
            "conventions": [],
            "ship_types": [],
            "excluded_types": [],
            "gt_min": None,
            "gt_max": None,
            "navigation": [],
            "flag_state": "JPN",
            "class_society": None,
            "radio_equipment": [],
            "build_year_before": None,
            "build_year_after": None,
        },
        "reason_template": "日本旗船として灯台表の備付義務",
    },
    {
        "publication_id": "JHO_TIDE_TABLES",
        "title": "Tide Tables (Japan)",
        "title_ja": "潮汐表",
        "category": CAT_B,
        "legal_basis": "船舶安全法 / 船舶設備規程",
        "publisher": "日本水路協会",
        "current_edition": "2026年版",
        "current_edition_date": "2026-01-01",
        "update_cycle": "年1回",
        "priority": MANDATORY,
        "applicability_rules": {
            "conventions": [],
            "ship_types": [],
            "excluded_types": [],
            "gt_min": None,
            "gt_max": None,
            "navigation": [],
            "flag_state": "JPN",
            "class_society": None,
            "radio_equipment": [],
            "build_year_before": None,
            "build_year_after": None,
        },
        "reason_template": "日本旗船として潮汐表の備付義務",
    },
    {
        "publication_id": "JHO_NAUTICAL_ALMANAC",
        "title": "Nautical Almanac",
        "title_ja": "天測暦",
        "category": CAT_B,
        "legal_basis": "船舶安全法 / 船舶設備規程",
        "publisher": "日本水路協会",
        "current_edition": "2026年版",
        "current_edition_date": "2026-01-01",
        "update_cycle": "年1回",
        "priority": MANDATORY,
        "applicability_rules": {
            "conventions": [],
            "ship_types": [],
            "excluded_types": [],
            "gt_min": None,
            "gt_max": None,
            "navigation": [],
            "flag_state": "JPN",
            "class_society": None,
            "radio_equipment": [],
            "build_year_before": None,
            "build_year_after": None,
        },
        "reason_template": "日本旗船として天測暦の備付義務",
    },
    {
        "publication_id": "JHO_NAUTICAL_ALMANAC_ABRIDGED",
        "title": "Abridged Nautical Almanac",
        "title_ja": "天測略暦",
        "category": CAT_B,
        "legal_basis": "船舶安全法 / 船舶設備規程",
        "publisher": "日本水路協会",
        "current_edition": "2026年版",
        "current_edition_date": "2026-01-01",
        "update_cycle": "年1回",
        "priority": RECOMMENDED,
        "applicability_rules": {
            "conventions": [],
            "ship_types": [],
            "excluded_types": [],
            "gt_min": None,
            "gt_max": None,
            "navigation": [],
            "flag_state": "JPN",
            "class_society": None,
            "radio_equipment": [],
            "build_year_before": None,
            "build_year_after": None,
        },
        "reason_template": "日本旗船として天測略暦の備付推奨",
    },
    {
        "publication_id": "JHO_DISTANCE_TABLES",
        "title": "Table of Distances",
        "title_ja": "距離表",
        "category": CAT_B,
        "legal_basis": "船舶安全法 / 船舶設備規程",
        "publisher": "日本水路協会",
        "current_edition": "最新版",
        "current_edition_date": None,
        "update_cycle": "不定期改訂",
        "priority": MANDATORY,
        "applicability_rules": {
            "conventions": [],
            "ship_types": [],
            "excluded_types": [],
            "gt_min": None,
            "gt_max": None,
            "navigation": [],
            "flag_state": "JPN",
            "class_society": None,
            "radio_equipment": [],
            "build_year_before": None,
            "build_year_after": None,
        },
        "reason_template": "日本旗船として距離表の備付義務",
    },
    {
        "publication_id": "JHO_NOTICES_TO_MARINERS",
        "title": "Notices to Mariners (Weekly)",
        "title_ja": "水路通報",
        "category": CAT_B,
        "legal_basis": "船舶安全法 / 水路業務法",
        "publisher": "海上保安庁",
        "current_edition": "最新号",
        "current_edition_date": None,
        "update_cycle": "週1回",
        "priority": MANDATORY,
        "applicability_rules": {
            "conventions": [],
            "ship_types": [],
            "excluded_types": [],
            "gt_min": None,
            "gt_max": None,
            "navigation": [],
            "flag_state": "JPN",
            "class_society": None,
            "radio_equipment": [],
            "build_year_before": None,
            "build_year_after": None,
        },
        "reason_template": "日本旗船として水路通報の備付義務",
    },
]

# ---------------------------------------------------------------------------
# UKHO (Admiralty)
# ---------------------------------------------------------------------------

UKHO_PUBLICATIONS: list[dict] = [
    {
        "publication_id": "ADMIRALTY_MARINERS_HANDBOOK",
        "title": "NP100 The Mariner's Handbook",
        "title_ja": "NP100 マリナーズハンドブック",
        "category": CAT_B,
        "legal_basis": "SOLAS Chapter V",
        "publisher": "UKHO (Admiralty)",
        "current_edition": "12th Edition (2020)",
        "current_edition_date": "2020-01-01",
        "update_cycle": "不定期改訂",
        "priority": MANDATORY,
        "applicability_rules": {
            "conventions": [],
            "ship_types": [],
            "excluded_types": [],
            "gt_min": None,
            "gt_max": None,
            "navigation": ["international"],
            "flag_state": None,
            "class_society": None,
            "radio_equipment": [],
            "build_year_before": None,
            "build_year_after": None,
        },
        "reason_template": "国際航行船舶にSOLAS V章に基づくNP100の備付義務",
    },
    {
        "publication_id": "ADMIRALTY_OCEAN_PASSAGES",
        "title": "NP136 Ocean Passages for the World",
        "title_ja": "NP136 世界の海上航路",
        "category": CAT_B,
        "legal_basis": "SOLAS Chapter V",
        "publisher": "UKHO (Admiralty)",
        "current_edition": "2021 Edition",
        "current_edition_date": "2021-01-01",
        "update_cycle": "不定期改訂",
        "priority": RECOMMENDED,
        "applicability_rules": {
            "conventions": [],
            "ship_types": [],
            "excluded_types": [],
            "gt_min": None,
            "gt_max": None,
            "navigation": ["international"],
            "flag_state": None,
            "class_society": None,
            "radio_equipment": [],
            "build_year_before": None,
            "build_year_after": None,
        },
        "reason_template": "国際航行船舶にNP136の備付推奨",
    },
    {
        "publication_id": "ADMIRALTY_LIST_OF_LIGHTS",
        "title": "Admiralty List of Lights and Fog Signals (NP74-84)",
        "title_ja": "英国水路部灯台表 (NP74-84)",
        "category": CAT_B,
        "legal_basis": "SOLAS Chapter V",
        "publisher": "UKHO (Admiralty)",
        "current_edition": "最新版",
        "current_edition_date": None,
        "update_cycle": "年1回",
        "priority": MANDATORY,
        "applicability_rules": {
            "conventions": [],
            "ship_types": [],
            "excluded_types": [],
            "gt_min": None,
            "gt_max": None,
            "navigation": ["international"],
            "flag_state": None,
            "class_society": None,
            "radio_equipment": [],
            "build_year_before": None,
            "build_year_after": None,
        },
        "reason_template": "国際航行船舶にAdmiralty灯台表の備付義務",
    },
    {
        "publication_id": "ADMIRALTY_TIDE_TABLES",
        "title": "Admiralty Tide Tables (NP201-204)",
        "title_ja": "英国水路部潮汐表 (NP201-204)",
        "category": CAT_B,
        "legal_basis": "SOLAS Chapter V",
        "publisher": "UKHO (Admiralty)",
        "current_edition": "最新版",
        "current_edition_date": None,
        "update_cycle": "年1回",
        "priority": MANDATORY,
        "applicability_rules": {
            "conventions": [],
            "ship_types": [],
            "excluded_types": [],
            "gt_min": None,
            "gt_max": None,
            "navigation": ["international"],
            "flag_state": None,
            "class_society": None,
            "radio_equipment": [],
            "build_year_before": None,
            "build_year_after": None,
        },
        "reason_template": "国際航行船舶にAdmiralty潮汐表の備付義務",
    },
    {
        "publication_id": "ADMIRALTY_SAILING_DIRECTIONS",
        "title": "Admiralty Sailing Directions (Pilots)",
        "title_ja": "英国水路部水路誌 (Pilots)",
        "category": CAT_B,
        "legal_basis": "SOLAS Chapter V",
        "publisher": "UKHO (Admiralty)",
        "current_edition": "最新版",
        "current_edition_date": None,
        "update_cycle": "不定期改訂",
        "priority": MANDATORY,
        "applicability_rules": {
            "conventions": [],
            "ship_types": [],
            "excluded_types": [],
            "gt_min": None,
            "gt_max": None,
            "navigation": ["international"],
            "flag_state": None,
            "class_society": None,
            "radio_equipment": [],
            "build_year_before": None,
            "build_year_after": None,
        },
        "reason_template": "国際航行船舶にAdmiralty水路誌の備付義務",
    },
]

# ---------------------------------------------------------------------------
# NGA (米国)
# ---------------------------------------------------------------------------

NGA_PUBLICATIONS: list[dict] = [
    {
        "publication_id": "NGA_AMERICAN_PRACTICAL_NAV",
        "title": "Pub. 9 The American Practical Navigator (Bowditch)",
        "title_ja": "Pub.9 米国実用航海書 (Bowditch)",
        "category": CAT_B,
        "legal_basis": "SOLAS Chapter V",
        "publisher": "NGA (National Geospatial-Intelligence Agency)",
        "current_edition": "2019 Edition",
        "current_edition_date": "2019-01-01",
        "update_cycle": "不定期改訂",
        "priority": RECOMMENDED,
        "applicability_rules": {
            "conventions": [],
            "ship_types": [],
            "excluded_types": [],
            "gt_min": None,
            "gt_max": None,
            "navigation": ["international"],
            "flag_state": None,
            "class_society": None,
            "radio_equipment": [],
            "build_year_before": None,
            "build_year_after": None,
        },
        "reason_template": "国際航行船舶にBowditchの備付推奨",
    },
    {
        "publication_id": "NGA_INT_CODE_OF_SIGNALS",
        "title": "Pub. 102 International Code of Signals (ICS)",
        "title_ja": "Pub.102 国際信号書",
        "category": CAT_B,
        "legal_basis": "SOLAS Chapter V, Reg. 21",
        "publisher": "NGA / IMO",
        "current_edition": "2005 Edition",
        "current_edition_date": "2005-01-01",
        "update_cycle": "不定期改訂",
        "priority": MANDATORY,
        "applicability_rules": {
            "conventions": [],
            "ship_types": [],
            "excluded_types": [],
            "gt_min": None,
            "gt_max": None,
            "navigation": ["international"],
            "flag_state": None,
            "class_society": None,
            "radio_equipment": [],
            "build_year_before": None,
            "build_year_after": None,
        },
        "reason_template": "SOLAS V章に基づく国際信号書の備付義務",
    },
    {
        "publication_id": "NGA_RADIO_NAV_AIDS",
        "title": "Pub. 117 Radio Navigational Aids",
        "title_ja": "Pub.117 無線航行援助書",
        "category": CAT_B,
        "legal_basis": "SOLAS Chapter V",
        "publisher": "NGA",
        "current_edition": "2017 Edition",
        "current_edition_date": "2017-01-01",
        "update_cycle": "不定期改訂",
        "priority": RECOMMENDED,
        "applicability_rules": {
            "conventions": [],
            "ship_types": [],
            "excluded_types": [],
            "gt_min": None,
            "gt_max": None,
            "navigation": ["international"],
            "flag_state": None,
            "class_society": None,
            "radio_equipment": [],
            "build_year_before": None,
            "build_year_after": None,
        },
        "reason_template": "国際航行船舶にPub.117の備付推奨",
    },
]


# ---------------------------------------------------------------------------
# ITU 無線関係刊行物
# ---------------------------------------------------------------------------

ITU_PUBLICATIONS: list[dict] = [
    {
        "publication_id": "ITU_LIST_COAST_STATIONS",
        "title": "List of Coast Stations and Special Service Stations (ITU List IV)",
        "title_ja": "海岸局及び特別業務局便覧 (ITU List IV)",
        "category": CAT_B,
        "legal_basis": "SOLAS Chapter IV + ITU Radio Regulations 12.3",
        "publisher": "ITU",
        "current_edition": "最新版",
        "current_edition_date": None,
        "update_cycle": "不定期（補遺あり）",
        "priority": MANDATORY,
        "applicability_rules": {
            "conventions": ["SOLAS"],
            "ship_types": [],
            "excluded_types": [],
            "gt_min": 300,
            "gt_max": None,
            "navigation": ["international"],
            "flag_state": None,
            "class_society": None,
            "radio_equipment": [],
            "build_year_before": None,
            "build_year_after": None,
        },
        "reason_template": "SOLAS IV章及びITU無線通信規則に基づくGMDSS船の法定備付書籍",
    },
    {
        "publication_id": "ITU_LIST_SHIP_STATIONS",
        "title": "List of Ship Stations and Maritime Mobile Service Identity Assignments (ITU List V)",
        "title_ja": "船舶局及びMMSI便覧 (ITU List V)",
        "category": CAT_B,
        "legal_basis": "SOLAS Chapter IV + ITU Radio Regulations 12.3",
        "publisher": "ITU",
        "current_edition": "最新版",
        "current_edition_date": None,
        "update_cycle": "不定期（補遺あり）",
        "priority": MANDATORY,
        "applicability_rules": {
            "conventions": ["SOLAS"],
            "ship_types": [],
            "excluded_types": [],
            "gt_min": 300,
            "gt_max": None,
            "navigation": ["international"],
            "flag_state": None,
            "class_society": None,
            "radio_equipment": [],
            "build_year_before": None,
            "build_year_after": None,
        },
        "reason_template": "SOLAS IV章及びITU無線通信規則に基づくGMDSS船の法定備付書籍",
    },
    {
        "publication_id": "ITU_MANUAL_MARITIME_MOBILE",
        "title": "Manual for Use by the Maritime Mobile and Maritime Mobile-Satellite Services",
        "title_ja": "海上移動業務及び海上移動衛星業務用マニュアル",
        "category": CAT_B,
        "legal_basis": "SOLAS Chapter IV + ITU Radio Regulations 12.3",
        "publisher": "ITU",
        "current_edition": "最新版",
        "current_edition_date": None,
        "update_cycle": "不定期",
        "priority": MANDATORY,
        "applicability_rules": {
            "conventions": ["SOLAS"],
            "ship_types": [],
            "excluded_types": [],
            "gt_min": 300,
            "gt_max": None,
            "navigation": ["international"],
            "flag_state": None,
            "class_society": None,
            "radio_equipment": [],
            "build_year_before": None,
            "build_year_after": None,
        },
        "reason_template": "SOLAS IV章及びITU無線通信規則に基づくGMDSS船の法定備付書籍",
    },
    {
        "publication_id": "JPN_RADIO_STATION_LIST",
        "title": "Japan Maritime Radio Station Directory",
        "title_ja": "日本海上関係無線局局名録",
        "category": CAT_B,
        "legal_basis": "電波法施行規則",
        "publisher": "情報通信振興会",
        "current_edition": "最新版",
        "current_edition_date": None,
        "update_cycle": "年1回",
        "priority": MANDATORY,
        "applicability_rules": {
            "conventions": [],
            "ship_types": [],
            "excluded_types": [],
            "gt_min": None,
            "gt_max": None,
            "navigation": [],
            "flag_state": "JPN",
            "class_society": None,
            "radio_equipment": [],
            "build_year_before": None,
            "build_year_after": None,
        },
        "reason_template": "日本旗船として電波法施行規則に基づく法定備付書籍",
    },
]


# ---------------------------------------------------------------------------
# 航海実務参考書（SMS管理図書 — 法定備置義務なし）
# ---------------------------------------------------------------------------

NAVIGATION_REFERENCE_PUBLICATIONS: list[dict] = [
    {
        "publication_id": "NAVIGATION_HANDBOOK",
        "title": "Navigation Handbook",
        "title_ja": "航海便覧",
        "category": CAT_B,
        "legal_basis": "SMS管理図書（法定備置義務なし）",
        "publisher": "海文堂",
        "current_edition": "最新版",
        "current_edition_date": None,
        "update_cycle": "不定期改訂",
        "priority": RECOMMENDED,
        "applicability_rules": {
            "conventions": [],
            "ship_types": [],
            "excluded_types": [],
            "gt_min": None,
            "gt_max": None,
            "navigation": [],
            "flag_state": "JPN",
            "class_society": None,
            "radio_equipment": [],
            "build_year_before": None,
            "build_year_after": None,
        },
        "reason_template": "SMS管理図書として航海便覧の備付を推奨（法定備置義務なし）",
    },
    {
        "publication_id": "EMERGENCY_ENTRY_HANDBOOK",
        "title": "Emergency Area Entry Handbook",
        "title_ja": "緊急入域ハンドブック",
        "category": CAT_B,
        "legal_basis": "SMS管理図書（法定備置義務なし）— IMO MSC.1/Circ.1521参考",
        "publisher": "海文堂",
        "current_edition": "最新版",
        "current_edition_date": None,
        "update_cycle": "不定期改訂",
        "priority": RECOMMENDED,
        "applicability_rules": {
            "conventions": [],
            "ship_types": [],
            "excluded_types": [],
            "gt_min": None,
            "gt_max": None,
            "navigation": ["international"],
            "flag_state": None,
            "class_society": None,
            "radio_equipment": [],
            "build_year_before": None,
            "build_year_after": None,
        },
        "reason_template": "SMS管理図書として緊急入域ハンドブックの備付を推奨（法定備置義務なし）",
    },
]
