"""
data_category_d.py — カテゴリD: 船上マニュアルマスターデータ (12件)
=================================================================
ISM/ISPS関連マニュアル、油濁防止計画、バラスト水管理計画等のデータ定義。
"""

from __future__ import annotations

from datetime import date

from .constants import (
    CAT_D,
    CARGO_SHIPS,
    CHEMICAL_CARRIERS,
    GAS_CARRIERS,
    MANDATORY,
    TANKER_TYPES,
)
from .data_category_a import _any_solas, _is_solas_ship


# ---------------------------------------------------------------------------
# カテゴリD: 船上マニュアルマスターデータ
# ---------------------------------------------------------------------------

CATEGORY_D_PUBLICATIONS: list[dict] = [
    # 56. SMS
    {
        "publication_id": "SMS_MANUAL",
        "title": "Safety Management Manual (SMS)",
        "title_ja": "安全管理マニュアル (SMS)",
        "category": CAT_D,
        "legal_basis": "ISM Code, Section 11",
        "publisher": "管理会社作成",
        "current_edition": "自社版最新",
        "current_edition_date": None,
        "update_cycle": "随時改訂",
        "priority": MANDATORY,
        "condition": lambda ship, conv_ids: "SOLAS_CH_IX_ISM" in conv_ids and _is_solas_ship(ship),
        "applicability_rules": {
            "conventions": ["SOLAS_CH_IX_ISM"],
            "ship_types": [],
            "excluded_types": [],
            "gt_min": 500,
            "gt_max": None,
            "navigation": ["international"],
            "flag_state": None,
            "class_society": None,
            "radio_equipment": [],
            "build_year_before": None,
            "build_year_after": None,
        },
        "reason_template": "ISM Code適用船舶としてSMSマニュアルの備付義務",
        "related_conventions_static": ["SOLAS_CH_IX_ISM"],
    },
    # 57. DOC
    {
        "publication_id": "DOC_CERTIFICATE",
        "title": "Document of Compliance (DOC) — Copy on board",
        "title_ja": "適合証書 (DOC) — 船上コピー",
        "category": CAT_D,
        "legal_basis": "ISM Code, Section 13",
        "publisher": "旗国/船級協会",
        "current_edition": "最新発行",
        "current_edition_date": None,
        "update_cycle": "5年ごと更新",
        "priority": MANDATORY,
        "condition": lambda ship, conv_ids: "SOLAS_CH_IX_ISM" in conv_ids and _is_solas_ship(ship),
        "applicability_rules": {
            "conventions": ["SOLAS_CH_IX_ISM"],
            "ship_types": [],
            "excluded_types": [],
            "gt_min": 500,
            "gt_max": None,
            "navigation": ["international"],
            "flag_state": None,
            "class_society": None,
            "radio_equipment": [],
            "build_year_before": None,
            "build_year_after": None,
        },
        "reason_template": "ISM Code適用船舶としてDOCコピーの船上備付義務",
        "related_conventions_static": ["SOLAS_CH_IX_ISM"],
    },
    # 58. CSM
    {
        "publication_id": "CARGO_SECURING_MANUAL",
        "title": "Cargo Securing Manual (CSM)",
        "title_ja": "貨物固縛マニュアル (CSM)",
        "category": CAT_D,
        "legal_basis": "SOLAS Chapter VI / CSS Code",
        "publisher": "船主・管理会社作成（船級承認）",
        "current_edition": "自船版最新",
        "current_edition_date": None,
        "update_cycle": "随時改訂",
        "priority": MANDATORY,
        "condition": lambda ship, conv_ids: ship.get("ship_type") in CARGO_SHIPS,
        "applicability_rules": {
            "conventions": [],
            "ship_types": CARGO_SHIPS[:],
            "excluded_types": [],
            "gt_min": None,
            "gt_max": None,
            "navigation": [],
            "flag_state": None,
            "class_society": None,
            "radio_equipment": [],
            "build_year_before": None,
            "build_year_after": None,
        },
        "reason_template": "貨物船として貨物固縛マニュアルの備付義務",
        "related_conventions_static": ["SOLAS_CH_VI_CARGO"],
    },
    # 59. SOPEP
    {
        "publication_id": "SOPEP",
        "title": "Shipboard Oil Pollution Emergency Plan (SOPEP)",
        "title_ja": "船舶油濁防止緊急措置手引書 (SOPEP)",
        "category": CAT_D,
        "legal_basis": "MARPOL Annex I, Reg. 37",
        "publisher": "管理会社作成（旗国承認）",
        "current_edition": "自船版最新",
        "current_edition_date": None,
        "update_cycle": "随時改訂",
        "priority": MANDATORY,
        "condition": lambda ship, conv_ids: (ship.get("gross_tonnage") or 0) >= 400,
        "applicability_rules": {
            "conventions": [],
            "ship_types": [],
            "excluded_types": [],
            "gt_min": 400,
            "gt_max": None,
            "navigation": [],
            "flag_state": None,
            "class_society": None,
            "radio_equipment": [],
            "build_year_before": None,
            "build_year_after": None,
        },
        "reason_template": "400GT以上の船舶にMARPOL Annex I Reg.37に基づくSOPEPの備付義務",
        "related_conventions_static": ["MARPOL_ANNEX_I"],
    },
    # 60. SMPEP
    {
        "publication_id": "SMPEP",
        "title": "Shipboard Marine Pollution Emergency Plan (SMPEP)",
        "title_ja": "船舶海洋汚染防止緊急措置手引書 (SMPEP)",
        "category": CAT_D,
        "legal_basis": "MARPOL Annex II / Protocol I",
        "publisher": "管理会社作成（旗国承認）",
        "current_edition": "自船版最新",
        "current_edition_date": None,
        "update_cycle": "随時改訂",
        "priority": MANDATORY,
        "condition": lambda ship, conv_ids: (
            ship.get("ship_type") in CHEMICAL_CARRIERS + GAS_CARRIERS
        ),
        "applicability_rules": {
            "conventions": [],
            "ship_types": CHEMICAL_CARRIERS + GAS_CARRIERS,
            "excluded_types": [],
            "gt_min": None,
            "gt_max": None,
            "navigation": [],
            "flag_state": None,
            "class_society": None,
            "radio_equipment": [],
            "build_year_before": None,
            "build_year_after": None,
        },
        "reason_template": "ケミカル/ガスキャリアとしてSMPEPの備付義務",
        "related_conventions_static": ["MARPOL_ANNEX_II"],
    },
    # 61. BWM Plan
    {
        "publication_id": "BWMP",
        "title": "Ballast Water Management Plan (BWMP)",
        "title_ja": "バラスト水管理計画書 (BWMP)",
        "category": CAT_D,
        "legal_basis": "BWM Convention, Reg. B-1",
        "publisher": "管理会社作成（旗国承認）",
        "current_edition": "自船版最新",
        "current_edition_date": None,
        "update_cycle": "随時改訂",
        "priority": MANDATORY,
        "condition": lambda ship, conv_ids: "BWM_CONVENTION" in conv_ids,
        "applicability_rules": {
            "conventions": ["BWM_CONVENTION"],
            "ship_types": [],
            "excluded_types": [],
            "gt_min": None,
            "gt_max": None,
            "navigation": [],
            "flag_state": None,
            "class_society": None,
            "radio_equipment": [],
            "build_year_before": None,
            "build_year_after": None,
        },
        "reason_template": "BWM条約適用船舶としてバラスト水管理計画書の備付義務",
        "related_conventions_static": ["BWM_CONVENTION"],
    },
    # 62. SSP
    {
        "publication_id": "SHIP_SECURITY_PLAN",
        "title": "Ship Security Plan (SSP)",
        "title_ja": "船舶保安計画書 (SSP)",
        "category": CAT_D,
        "legal_basis": "ISPS Code, Part A, Section 9",
        "publisher": "管理会社作成（旗国承認）",
        "current_edition": "自船版最新",
        "current_edition_date": None,
        "update_cycle": "随時改訂",
        "priority": MANDATORY,
        "condition": lambda ship, conv_ids: "SOLAS_CH_XI2_ISPS" in conv_ids and _is_solas_ship(ship),
        "applicability_rules": {
            "conventions": ["SOLAS_CH_XI2_ISPS"],
            "ship_types": [],
            "excluded_types": [],
            "gt_min": 500,
            "gt_max": None,
            "navigation": ["international"],
            "flag_state": None,
            "class_society": None,
            "radio_equipment": [],
            "build_year_before": None,
            "build_year_after": None,
        },
        "reason_template": "ISPS Code適用船舶として船舶保安計画書の備付義務",
        "related_conventions_static": ["SOLAS_CH_XI2_ISPS"],
    },
    # 63. Garbage Management Plan
    {
        "publication_id": "GARBAGE_MANAGEMENT_PLAN",
        "title": "Garbage Management Plan",
        "title_ja": "廃棄物管理計画書",
        "category": CAT_D,
        "legal_basis": "MARPOL Annex V, Reg. 10.2",
        "publisher": "管理会社作成",
        "current_edition": "自船版最新",
        "current_edition_date": None,
        "update_cycle": "随時改訂",
        "priority": MANDATORY,
        "condition": lambda ship, conv_ids: True,  # 全船（MARPOL V）
        "applicability_rules": {
            "conventions": [],
            "ship_types": [],
            "excluded_types": [],
            "gt_min": None,
            "gt_max": None,
            "navigation": [],
            "flag_state": None,
            "class_society": None,
            "radio_equipment": [],
            "build_year_before": None,
            "build_year_after": None,
        },
        "reason_template": "全ての船舶にMARPOL Annex V Reg.10.2に基づく廃棄物管理計画書の備付義務",
        "related_conventions_static": ["MARPOL_ANNEX_V"],
    },
    # 64. SEEMP
    {
        "publication_id": "SEEMP",
        "title": "Ship Energy Efficiency Management Plan (SEEMP)",
        "title_ja": "船舶エネルギー効率管理計画書 (SEEMP)",
        "category": CAT_D,
        "legal_basis": "MARPOL Annex VI, Reg. 26",
        "publisher": "管理会社作成（旗国承認）",
        "current_edition": "Part I & Part II (CII)",
        "current_edition_date": None,
        "update_cycle": "随時改訂",
        "priority": MANDATORY,
        "condition": lambda ship, conv_ids: (ship.get("gross_tonnage") or 0) >= 400,
        "applicability_rules": {
            "conventions": [],
            "ship_types": [],
            "excluded_types": [],
            "gt_min": 400,
            "gt_max": None,
            "navigation": [],
            "flag_state": None,
            "class_society": None,
            "radio_equipment": [],
            "build_year_before": None,
            "build_year_after": None,
        },
        "reason_template": "400GT以上の船舶にMARPOL Annex VI Reg.26に基づくSEEMPの備付義務",
        "related_conventions_static": ["MARPOL_ANNEX_VI_AIR", "MARPOL_ANNEX_VI_GHG"],
    },
    # 65. VOC Management Plan
    {
        "publication_id": "VOC_MANAGEMENT_PLAN",
        "title": "VOC Management Plan",
        "title_ja": "揮発性有機化合物管理計画書 (VOC)",
        "category": CAT_D,
        "legal_basis": "MARPOL Annex VI, Reg. 15",
        "publisher": "管理会社作成",
        "current_edition": "自船版最新",
        "current_edition_date": None,
        "update_cycle": "随時改訂",
        "priority": MANDATORY,
        "condition": lambda ship, conv_ids: ship.get("ship_type") in TANKER_TYPES,
        "applicability_rules": {
            "conventions": [],
            "ship_types": TANKER_TYPES[:],
            "excluded_types": [],
            "gt_min": None,
            "gt_max": None,
            "navigation": [],
            "flag_state": None,
            "class_society": None,
            "radio_equipment": [],
            "build_year_before": None,
            "build_year_after": None,
        },
        "reason_template": "タンカーとしてMARPOL Annex VI Reg.15に基づくVOC管理計画の備付義務",
        "related_conventions_static": ["MARPOL_ANNEX_VI_AIR"],
    },
    # 66. CAS Record
    {
        "publication_id": "CAS_RECORD",
        "title": "Condition Assessment Scheme Record (CAS)",
        "title_ja": "船体状態評価記録 (CAS)",
        "category": CAT_D,
        "legal_basis": "MARPOL Annex I, Reg. 20 / 21",
        "publisher": "船級協会",
        "current_edition": "自船版最新",
        "current_edition_date": None,
        "update_cycle": "中間検査時",
        "priority": MANDATORY,
        "condition": lambda ship, conv_ids: (
            ship.get("ship_type") in TANKER_TYPES
            and (ship.get("build_year") or 2020) <= (date.today().year - 15)
        ),
        "applicability_rules": {
            "conventions": [],
            "ship_types": TANKER_TYPES[:],
            "excluded_types": [],
            "gt_min": None,
            "gt_max": None,
            "navigation": [],
            "flag_state": None,
            "class_society": None,
            "radio_equipment": [],
            "build_year_before": None,
            "build_year_after": None,
        },
        "reason_template": "船齢15年超のタンカーとしてCAS記録の備付義務",
        "related_conventions_static": ["MARPOL_ANNEX_I", "MARPOL_I_TANKER"],
    },
    # 67. CSR (Continuous Synopsis Record)
    {
        "publication_id": "CONTINUOUS_SYNOPSIS_RECORD",
        "title": "Continuous Synopsis Record (CSR)",
        "title_ja": "継続概要記録簿 (CSR)",
        "category": CAT_D,
        "legal_basis": "SOLAS Chapter XI-1, Reg. 5",
        "publisher": "旗国発行",
        "current_edition": "最新版",
        "current_edition_date": None,
        "update_cycle": "変更の都度",
        "priority": MANDATORY,
        "condition": lambda ship, conv_ids: _any_solas(conv_ids, ship),
        "applicability_rules": {
            "conventions": ["SOLAS"],
            "ship_types": [],
            "excluded_types": [],
            "gt_min": 500,
            "gt_max": None,
            "navigation": ["international"],
            "flag_state": None,
            "class_society": None,
            "radio_equipment": [],
            "build_year_before": None,
            "build_year_after": None,
        },
        "reason_template": "全ての条約適用船舶にSOLAS XI-1 Reg.5に基づくCSRの備付義務",
        "related_conventions_static": ["SOLAS_CH_XI1_ESP"],
    },
]
