"""
data_category_a.py — カテゴリA: 条約書籍マスターデータ (27件)
=============================================================
IMO条約・コードに基づく備付書籍のデータ定義。
"""

from __future__ import annotations

from .constants import (
    CAT_A,
    CARGO_SHIPS,
    CHEMICAL_CARRIERS,
    GAS_CARRIERS,
    MANDATORY,
    RECOMMENDED,
)


# ---------------------------------------------------------------------------
# ヘルパー関数（lambda から参照）
# ---------------------------------------------------------------------------

def _is_solas_ship(ship: dict) -> bool:
    """SOLAS条約船かどうか（500GT以上かつ国際航行）"""
    gt = ship.get("gross_tonnage") or 0
    return gt >= 500 and _is_international(ship)


def _any_solas(conv_ids: set[str], ship: dict | None = None) -> bool:
    """適用条約にいずれかのSOLAS章が含まれるか（ship指定時はGT/航行区域も確認）"""
    has_solas = any(cid.startswith("SOLAS") for cid in conv_ids)
    if ship is not None:
        return has_solas and _is_solas_ship(ship)
    return has_solas


def _any_marpol(conv_ids: set[str]) -> bool:
    """適用条約にいずれかのMARPOL附属書が含まれるか"""
    return any(cid.startswith("MARPOL") for cid in conv_ids)


def _is_international(ship: dict) -> bool:
    """国際航行船舶かどうか"""
    nav = ship.get("navigation_area") or []
    if isinstance(nav, str):
        nav = [nav]
    return "international" in nav


# ---------------------------------------------------------------------------
# カテゴリA: 条約書籍マスターデータ
# ---------------------------------------------------------------------------

CATEGORY_A_PUBLICATIONS: list[dict] = [
    # 1. SOLAS
    {
        "publication_id": "SOLAS_CONSOLIDATED",
        "title": "SOLAS Consolidated Edition 2024",
        "title_ja": "SOLAS統合版 2024",
        "category": CAT_A,
        "legal_basis": "SOLAS 1974 as amended",
        "publisher": "IMO",
        "current_edition": "2024 Edition",
        "current_edition_date": "2024-01-01",
        "update_cycle": "約2〜3年ごとに統合版刊行",
        "priority": MANDATORY,
        "convention_trigger": "SOLAS",
        "condition": lambda ship, conv_ids: _any_solas(conv_ids, ship),
        "applicability_rules": {
            "conventions": ["SOLAS"],
            "ship_types": [],
            "excluded_types": [],
            "gt_min": 500,
            "gt_max": None,
            "navigation": ["international"],
            "flag_state": None,
            "class_society": None,
            "radio_equipment": [],
            "build_year_before": None,
            "build_year_after": None,
        },
        "reason_template": "SOLAS適用船舶として全SOLAS章に基づく規則の備付義務",
    },
    # 2. MARPOL
    {
        "publication_id": "MARPOL_CONSOLIDATED",
        "title": "MARPOL Consolidated Edition (Annex I-VI)",
        "title_ja": "MARPOL統合版 (附属書I〜VI)",
        "category": CAT_A,
        "legal_basis": "MARPOL 73/78",
        "publisher": "IMO",
        "current_edition": "2022 Edition",
        "current_edition_date": "2022-01-01",
        "update_cycle": "約3年ごとに統合版刊行",
        "priority": MANDATORY,
        "convention_trigger": "MARPOL",
        "condition": lambda ship, conv_ids: _any_marpol(conv_ids),
        "applicability_rules": {
            "conventions": ["MARPOL"],
            "ship_types": [],
            "excluded_types": [],
            "gt_min": None,
            "gt_max": None,
            "navigation": [],
            "flag_state": None,
            "class_society": None,
            "radio_equipment": [],
            "build_year_before": None,
            "build_year_after": None,
        },
        "reason_template": "MARPOL適用船舶として海洋汚染防止条約の備付義務",
    },
    # 3. IMDG Code
    {
        "publication_id": "IMDG_CODE",
        "title": "IMDG Code (Amendment 42-24)",
        "title_ja": "国際海上危険物規程 (改正42-24)",
        "category": CAT_A,
        "legal_basis": "SOLAS Chapter VII",
        "publisher": "IMO",
        "current_edition": "Amendment 42-24",
        "current_edition_date": "2024-01-01",
        "update_cycle": "2年ごと改正",
        "priority": MANDATORY,
        "convention_trigger": "SOLAS_CH_VII_DG",
        "condition": lambda ship, conv_ids: (
            "SOLAS_CH_VII_DG" in conv_ids
            and ship.get("ship_type") in CARGO_SHIPS
            and _is_solas_ship(ship)
        ),
        "applicability_rules": {
            "conventions": ["SOLAS_CH_VII_DG"],
            "ship_types": CARGO_SHIPS[:],
            "excluded_types": [],
            "gt_min": 500,
            "gt_max": None,
            "navigation": ["international"],
            "flag_state": None,
            "class_society": None,
            "radio_equipment": [],
            "build_year_before": None,
            "build_year_after": None,
        },
        "reason_template": "SOLAS VII章適用貨物船として危険物運送規程の備付義務",
    },
    # 4. IBC Code
    {
        "publication_id": "IBC_CODE",
        "title": "IBC Code (International Code for the Construction and Equipment of Ships Carrying Dangerous Chemicals in Bulk)",
        "title_ja": "国際バルクケミカルコード (IBC Code)",
        "category": CAT_A,
        "legal_basis": "SOLAS VII / MARPOL Annex II",
        "publisher": "IMO",
        "current_edition": "2022 Edition",
        "current_edition_date": "2022-01-01",
        "update_cycle": "不定期改正",
        "priority": MANDATORY,
        "convention_trigger": "IBC_CODE",
        "condition": lambda ship, conv_ids: (
            ship.get("ship_type") in CHEMICAL_CARRIERS
        ),
        "applicability_rules": {
            "conventions": [],
            "ship_types": CHEMICAL_CARRIERS[:],
            "excluded_types": [],
            "gt_min": None,
            "gt_max": None,
            "navigation": [],
            "flag_state": None,
            "class_society": None,
            "radio_equipment": [],
            "build_year_before": None,
            "build_year_after": None,
        },
        "reason_template": "ケミカルタンカーとしてIBCコードに基づく備付義務",
    },
    # 5. IGC Code
    {
        "publication_id": "IGC_CODE",
        "title": "IGC Code (International Code for the Construction and Equipment of Ships Carrying Liquefied Gases in Bulk)",
        "title_ja": "国際ガスキャリアコード (IGC Code)",
        "category": CAT_A,
        "legal_basis": "SOLAS Chapter VII",
        "publisher": "IMO",
        "current_edition": "2016 Edition",
        "current_edition_date": "2016-01-01",
        "update_cycle": "不定期改正",
        "priority": MANDATORY,
        "convention_trigger": "IGC_CODE",
        "condition": lambda ship, conv_ids: (
            ship.get("ship_type") in GAS_CARRIERS
        ),
        "applicability_rules": {
            "conventions": [],
            "ship_types": GAS_CARRIERS[:],
            "excluded_types": [],
            "gt_min": None,
            "gt_max": None,
            "navigation": [],
            "flag_state": None,
            "class_society": None,
            "radio_equipment": [],
            "build_year_before": None,
            "build_year_after": None,
        },
        "reason_template": "LPG/LNG船としてIGCコードに基づく備付義務",
    },
    # 6. BCH Code
    {
        "publication_id": "BCH_CODE",
        "title": "BCH Code (Code for the Construction and Equipment of Ships Carrying Dangerous Chemicals in Bulk)",
        "title_ja": "BCHコード (旧船ケミカル)",
        "category": CAT_A,
        "legal_basis": "MARPOL Annex II / SOLAS VII",
        "publisher": "IMO",
        "current_edition": "2008 Edition",
        "current_edition_date": "2008-01-01",
        "update_cycle": "不定期",
        "priority": MANDATORY,
        "convention_trigger": "IBC_CODE",
        "condition": lambda ship, conv_ids: (
            ship.get("ship_type") in CHEMICAL_CARRIERS
            and (ship.get("build_year") or 2000) < 1986
        ),
        "applicability_rules": {
            "conventions": [],
            "ship_types": CHEMICAL_CARRIERS[:],
            "excluded_types": [],
            "gt_min": None,
            "gt_max": None,
            "navigation": [],
            "flag_state": None,
            "class_society": None,
            "radio_equipment": [],
            "build_year_before": 1986,
            "build_year_after": None,
        },
        "reason_template": "1986年以前建造のケミカルタンカーとしてBCHコードに基づく備付義務",
    },
    # 7. ISM Code
    {
        "publication_id": "ISM_CODE",
        "title": "ISM Code (International Safety Management Code)",
        "title_ja": "国際安全管理コード (ISM Code)",
        "category": CAT_A,
        "legal_basis": "SOLAS Chapter IX",
        "publisher": "IMO",
        "current_edition": "2018 Edition",
        "current_edition_date": "2018-01-01",
        "update_cycle": "不定期改正",
        "priority": MANDATORY,
        "convention_trigger": "SOLAS_CH_IX_ISM",
        "condition": lambda ship, conv_ids: (
            "SOLAS_CH_IX_ISM" in conv_ids and _is_solas_ship(ship)
        ),
        "applicability_rules": {
            "conventions": ["SOLAS_CH_IX_ISM"],
            "ship_types": [],
            "excluded_types": [],
            "gt_min": 500,
            "gt_max": None,
            "navigation": ["international"],
            "flag_state": None,
            "class_society": None,
            "radio_equipment": [],
            "build_year_before": None,
            "build_year_after": None,
        },
        "reason_template": "500GT以上の国際航行船舶にSOLAS IX章に基づくISMコードの備付義務",
    },
    # 8. ISPS Code
    {
        "publication_id": "ISPS_CODE",
        "title": "ISPS Code (International Ship and Port Facility Security Code)",
        "title_ja": "国際船舶・港湾施設保安コード (ISPS Code)",
        "category": CAT_A,
        "legal_basis": "SOLAS Chapter XI-2",
        "publisher": "IMO",
        "current_edition": "2003 Edition (with amendments)",
        "current_edition_date": "2003-12-01",
        "update_cycle": "不定期改正",
        "priority": MANDATORY,
        "convention_trigger": "SOLAS_CH_XI2_ISPS",
        "condition": lambda ship, conv_ids: (
            "SOLAS_CH_XI2_ISPS" in conv_ids and _is_solas_ship(ship)
        ),
        "applicability_rules": {
            "conventions": ["SOLAS_CH_XI2_ISPS"],
            "ship_types": [],
            "excluded_types": [],
            "gt_min": 500,
            "gt_max": None,
            "navigation": ["international"],
            "flag_state": None,
            "class_society": None,
            "radio_equipment": [],
            "build_year_before": None,
            "build_year_after": None,
        },
        "reason_template": "500GT以上の国際航行船舶にSOLAS XI-2章に基づくISPSコードの備付義務",
    },
    # 9. STCW Convention & Code
    {
        "publication_id": "STCW_CODE",
        "title": "STCW Convention and STCW Code",
        "title_ja": "船員の訓練・資格証明・当直基準条約及びコード (STCW)",
        "category": CAT_A,
        "legal_basis": "STCW 1978 as amended (Manila 2010)",
        "publisher": "IMO",
        "current_edition": "2017 Edition",
        "current_edition_date": "2017-01-01",
        "update_cycle": "不定期改正",
        "priority": MANDATORY,
        "convention_trigger": "STCW",
        "condition": lambda ship, conv_ids: True,  # 全条約船
        "applicability_rules": {
            "conventions": [],
            "ship_types": [],
            "excluded_types": [],
            "gt_min": None,
            "gt_max": None,
            "navigation": [],
            "flag_state": None,
            "class_society": None,
            "radio_equipment": [],
            "build_year_before": None,
            "build_year_after": None,
        },
        "reason_template": "全ての条約適用船舶にSTCW条約・コードの備付義務",
    },
    # 10. MLC 2006
    {
        "publication_id": "MLC_2006",
        "title": "Maritime Labour Convention, 2006 (MLC)",
        "title_ja": "海上労働条約 2006 (MLC)",
        "category": CAT_A,
        "legal_basis": "MLC 2006 as amended",
        "publisher": "ILO",
        "current_edition": "2022 Consolidated Edition",
        "current_edition_date": "2022-01-01",
        "update_cycle": "不定期改正",
        "priority": MANDATORY,
        "convention_trigger": "MLC_2006",
        "condition": lambda ship, conv_ids: True,  # 全船
        "applicability_rules": {
            "conventions": [],
            "ship_types": [],
            "excluded_types": [],
            "gt_min": None,
            "gt_max": None,
            "navigation": [],
            "flag_state": None,
            "class_society": None,
            "radio_equipment": [],
            "build_year_before": None,
            "build_year_after": None,
        },
        "reason_template": "全ての船舶に海上労働条約の備付義務",
    },
    # 11. COLREG
    {
        "publication_id": "COLREG_1972",
        "title": "COLREG 1972 (Convention on the International Regulations for Preventing Collisions at Sea)",
        "title_ja": "1972年海上衝突予防規則条約 (COLREG)",
        "category": CAT_A,
        "legal_basis": "COLREG 1972",
        "publisher": "IMO",
        "current_edition": "2003 Consolidated Edition",
        "current_edition_date": "2003-01-01",
        "update_cycle": "不定期改正",
        "priority": MANDATORY,
        "convention_trigger": "COLREG",
        "condition": lambda ship, conv_ids: True,  # 全船
        "applicability_rules": {
            "conventions": [],
            "ship_types": [],
            "excluded_types": [],
            "gt_min": None,
            "gt_max": None,
            "navigation": [],
            "flag_state": None,
            "class_society": None,
            "radio_equipment": [],
            "build_year_before": None,
            "build_year_after": None,
        },
        "reason_template": "全ての船舶に海上衝突予防規則の備付義務",
    },
    # 12. Load Lines Convention
    {
        "publication_id": "LOAD_LINES",
        "title": "International Convention on Load Lines, 1966 / Protocol 1988",
        "title_ja": "国際満載喫水線条約 1966 / 1988年議定書",
        "category": CAT_A,
        "legal_basis": "Load Lines 1966/1988",
        "publisher": "IMO",
        "current_edition": "2021 Edition",
        "current_edition_date": "2021-01-01",
        "update_cycle": "不定期改正",
        "priority": MANDATORY,
        "convention_trigger": "LOAD_LINE",
        "condition": lambda ship, conv_ids: _is_international(ship),
        "applicability_rules": {
            "conventions": [],
            "ship_types": [],
            "excluded_types": [],
            "gt_min": None,
            "gt_max": None,
            "navigation": ["international"],
            "flag_state": None,
            "class_society": None,
            "radio_equipment": [],
            "build_year_before": None,
            "build_year_after": None,
        },
        "reason_template": "国際航行船舶に満載喫水線条約に基づく備付義務",
    },
    # 13. Tonnage Convention
    {
        "publication_id": "TONNAGE_1969",
        "title": "International Convention on Tonnage Measurement of Ships, 1969",
        "title_ja": "1969年船舶トン数測度条約",
        "category": CAT_A,
        "legal_basis": "Tonnage Convention 1969",
        "publisher": "IMO",
        "current_edition": "1982 Edition",
        "current_edition_date": "1982-01-01",
        "update_cycle": "改正頻度低",
        "priority": MANDATORY,
        "convention_trigger": "TONNAGE_CONVENTION",
        "condition": lambda ship, conv_ids: _is_international(ship),
        "applicability_rules": {
            "conventions": [],
            "ship_types": [],
            "excluded_types": [],
            "gt_min": None,
            "gt_max": None,
            "navigation": ["international"],
            "flag_state": None,
            "class_society": None,
            "radio_equipment": [],
            "build_year_before": None,
            "build_year_after": None,
        },
        "reason_template": "国際航行船舶にトン数測度条約に基づく備付義務",
    },
    # 14. IAMSAR Manual Vol.III
    {
        "publication_id": "IAMSAR_VOL3",
        "title": "IAMSAR Manual Volume III (Mobile Facilities)",
        "title_ja": "国際航空海上捜索救助マニュアル 第III巻 (船上用)",
        "category": CAT_A,
        "legal_basis": "SOLAS Chapter V, Reg. 21",
        "publisher": "IMO / ICAO",
        "current_edition": "2022 Edition",
        "current_edition_date": "2022-01-01",
        "update_cycle": "約3年ごと",
        "priority": MANDATORY,
        "convention_trigger": "SOLAS_CH_V_NAVIGATION",
        "condition": lambda ship, conv_ids: (
            "SOLAS_CH_V_NAVIGATION" in conv_ids and _is_solas_ship(ship)
        ),
        "applicability_rules": {
            "conventions": ["SOLAS_CH_V_NAVIGATION"],
            "ship_types": [],
            "excluded_types": [],
            "gt_min": 500,
            "gt_max": None,
            "navigation": ["international"],
            "flag_state": None,
            "class_society": None,
            "radio_equipment": [],
            "build_year_before": None,
            "build_year_after": None,
        },
        "reason_template": "SOLAS V章適用船舶にIAMSARマニュアルの備付義務（Reg. V/21）",
    },
    # 15. LSA Code
    {
        "publication_id": "LSA_CODE",
        "title": "LSA Code (International Life-Saving Appliance Code)",
        "title_ja": "国際救命設備コード (LSA Code)",
        "category": CAT_A,
        "legal_basis": "SOLAS Chapter III",
        "publisher": "IMO",
        "current_edition": "2023 Edition",
        "current_edition_date": "2023-01-01",
        "update_cycle": "不定期改正",
        "priority": MANDATORY,
        "convention_trigger": "SOLAS_CH_III_LSA",
        "condition": lambda ship, conv_ids: _any_solas(conv_ids, ship),
        "applicability_rules": {
            "conventions": ["SOLAS"],
            "ship_types": [],
            "excluded_types": [],
            "gt_min": 500,
            "gt_max": None,
            "navigation": ["international"],
            "flag_state": None,
            "class_society": None,
            "radio_equipment": [],
            "build_year_before": None,
            "build_year_after": None,
        },
        "reason_template": "SOLAS適用船舶にLSAコードの備付義務",
    },
    # 16. FSS Code
    {
        "publication_id": "FSS_CODE",
        "title": "FSS Code (International Code for Fire Safety Systems)",
        "title_ja": "国際火災安全システムコード (FSS Code)",
        "category": CAT_A,
        "legal_basis": "SOLAS Chapter II-2",
        "publisher": "IMO",
        "current_edition": "2015 Edition",
        "current_edition_date": "2015-01-01",
        "update_cycle": "不定期改正",
        "priority": MANDATORY,
        "convention_trigger": "SOLAS_CH_II2_FIRE",
        "condition": lambda ship, conv_ids: _any_solas(conv_ids, ship),
        "applicability_rules": {
            "conventions": ["SOLAS"],
            "ship_types": [],
            "excluded_types": [],
            "gt_min": 500,
            "gt_max": None,
            "navigation": ["international"],
            "flag_state": None,
            "class_society": None,
            "radio_equipment": [],
            "build_year_before": None,
            "build_year_after": None,
        },
        "reason_template": "SOLAS適用船舶にFSSコードの備付義務",
    },
    # 17. FTP Code
    {
        "publication_id": "FTP_CODE",
        "title": "FTP Code (International Code for Application of Fire Test Procedures)",
        "title_ja": "国際耐火試験手順コード (FTP Code)",
        "category": CAT_A,
        "legal_basis": "SOLAS Chapter II-2",
        "publisher": "IMO",
        "current_edition": "2010 Edition (2012 FTP Code)",
        "current_edition_date": "2012-01-01",
        "update_cycle": "不定期改正",
        "priority": MANDATORY,
        "convention_trigger": "SOLAS_CH_II2_FIRE",
        "condition": lambda ship, conv_ids: _any_solas(conv_ids, ship),
        "applicability_rules": {
            "conventions": ["SOLAS"],
            "ship_types": [],
            "excluded_types": [],
            "gt_min": 500,
            "gt_max": None,
            "navigation": ["international"],
            "flag_state": None,
            "class_society": None,
            "radio_equipment": [],
            "build_year_before": None,
            "build_year_after": None,
        },
        "reason_template": "SOLAS適用船舶にFTPコードの備付義務",
    },
    # 18. CSS Code
    {
        "publication_id": "CSS_CODE",
        "title": "CSS Code (Code of Safe Practice for Cargo Stowage and Securing)",
        "title_ja": "貨物積付・固定安全実施要綱 (CSS Code)",
        "category": CAT_A,
        "legal_basis": "SOLAS Chapter VI",
        "publisher": "IMO",
        "current_edition": "2021 Edition",
        "current_edition_date": "2021-01-01",
        "update_cycle": "不定期改正",
        "priority": MANDATORY,
        "convention_trigger": "SOLAS_CH_VI_CARGO",
        "condition": lambda ship, conv_ids: ship.get("ship_type") in CARGO_SHIPS,
        "applicability_rules": {
            "conventions": [],
            "ship_types": CARGO_SHIPS[:],
            "excluded_types": [],
            "gt_min": None,
            "gt_max": None,
            "navigation": [],
            "flag_state": None,
            "class_society": None,
            "radio_equipment": [],
            "build_year_before": None,
            "build_year_after": None,
        },
        "reason_template": "貨物船としてCSSコードに基づく備付義務",
    },
    # 19. Grain Code
    {
        "publication_id": "GRAIN_CODE",
        "title": "International Code for the Safe Carriage of Grain in Bulk (International Grain Code)",
        "title_ja": "穀類運送国際コード (Grain Code)",
        "category": CAT_A,
        "legal_basis": "SOLAS Chapter VI, Part C",
        "publisher": "IMO",
        "current_edition": "1991 Edition",
        "current_edition_date": "1991-01-01",
        "update_cycle": "改正頻度低",
        "priority": MANDATORY,
        "convention_trigger": "SOLAS_CH_VI_CARGO",
        "condition": lambda ship, conv_ids: ship.get("ship_type") in ["bulk_carrier", "general_cargo"],
        "applicability_rules": {
            "conventions": [],
            "ship_types": ["bulk_carrier", "general_cargo"],
            "excluded_types": [],
            "gt_min": None,
            "gt_max": None,
            "navigation": [],
            "flag_state": None,
            "class_society": None,
            "radio_equipment": [],
            "build_year_before": None,
            "build_year_after": None,
        },
        "reason_template": "穀類運送可能船舶としてGrain Codeの備付義務",
    },
    # 20. ESP Code
    {
        "publication_id": "ESP_CODE",
        "title": "ESP Code (Enhanced Survey Programme)",
        "title_ja": "強化検査プログラムコード (ESP Code)",
        "category": CAT_A,
        "legal_basis": "SOLAS Chapter XI-1, Reg. 2",
        "publisher": "IMO",
        "current_edition": "2022 Edition",
        "current_edition_date": "2022-01-01",
        "update_cycle": "不定期改正",
        "priority": MANDATORY,
        "convention_trigger": "SOLAS_CH_XI1_ESP",
        "condition": lambda ship, conv_ids: (
            ship.get("ship_type") in ["bulk_carrier", "tanker"]
            and _is_solas_ship(ship)
        ),
        "applicability_rules": {
            "conventions": [],
            "ship_types": ["bulk_carrier", "tanker"],
            "excluded_types": [],
            "gt_min": 500,
            "gt_max": None,
            "navigation": ["international"],
            "flag_state": None,
            "class_society": None,
            "radio_equipment": [],
            "build_year_before": None,
            "build_year_after": None,
        },
        "reason_template": "バルカー・タンカーとしてESPコードに基づく強化検査の備付義務",
    },
    # 21. BWM Convention
    {
        "publication_id": "BWM_CONVENTION",
        "title": "International Convention for the Control and Management of Ships' Ballast Water and Sediments (BWM Convention)",
        "title_ja": "バラスト水管理条約 (BWM Convention)",
        "category": CAT_A,
        "legal_basis": "BWM Convention 2004",
        "publisher": "IMO",
        "current_edition": "2004 Edition (with 2024 amendments)",
        "current_edition_date": "2024-01-01",
        "update_cycle": "不定期改正",
        "priority": MANDATORY,
        "convention_trigger": "BWM_CONVENTION",
        "condition": lambda ship, conv_ids: "BWM_CONVENTION" in conv_ids,
        "applicability_rules": {
            "conventions": ["BWM_CONVENTION"],
            "ship_types": [],
            "excluded_types": [],
            "gt_min": None,
            "gt_max": None,
            "navigation": [],
            "flag_state": None,
            "class_society": None,
            "radio_equipment": [],
            "build_year_before": None,
            "build_year_after": None,
        },
        "reason_template": "バラスト水管理条約適用船舶としてBWM条約の備付義務",
    },
    # 22. AFS Convention
    {
        "publication_id": "AFS_CONVENTION",
        "title": "AFS Convention (International Convention on the Control of Harmful Anti-Fouling Systems on Ships)",
        "title_ja": "船舶有害防汚方法規制条約 (AFS Convention)",
        "category": CAT_A,
        "legal_basis": "AFS Convention 2001",
        "publisher": "IMO",
        "current_edition": "2001 Edition (with amendments)",
        "current_edition_date": "2001-10-05",
        "update_cycle": "不定期改正",
        "priority": MANDATORY,
        "convention_trigger": "AFS_CONVENTION",
        "condition": lambda ship, conv_ids: True,  # 全船
        "applicability_rules": {
            "conventions": [],
            "ship_types": [],
            "excluded_types": [],
            "gt_min": None,
            "gt_max": None,
            "navigation": [],
            "flag_state": None,
            "class_society": None,
            "radio_equipment": [],
            "build_year_before": None,
            "build_year_after": None,
        },
        "reason_template": "全ての船舶にAFS条約に基づく備付義務",
    },
    # 23. Hong Kong Convention
    {
        "publication_id": "HONG_KONG_CONVENTION",
        "title": "Hong Kong International Convention for the Safe and Environmentally Sound Recycling of Ships, 2009",
        "title_ja": "シップリサイクル条約 (香港条約)",
        "category": CAT_A,
        "legal_basis": "Hong Kong Convention 2009",
        "publisher": "IMO",
        "current_edition": "2009 Edition",
        "current_edition_date": "2009-05-15",
        "update_cycle": "発効後改正予定",
        "priority": MANDATORY,
        "convention_trigger": "SHIP_RECYCLING_HKC",
        "condition": lambda ship, conv_ids: True,  # 全船
        "applicability_rules": {
            "conventions": [],
            "ship_types": [],
            "excluded_types": [],
            "gt_min": None,
            "gt_max": None,
            "navigation": [],
            "flag_state": None,
            "class_society": None,
            "radio_equipment": [],
            "build_year_before": None,
            "build_year_after": None,
        },
        "reason_template": "全ての船舶に香港条約に基づく備付義務",
    },
    # 24. Nairobi WRC
    {
        "publication_id": "NAIROBI_WRC",
        "title": "Nairobi International Convention on the Removal of Wrecks, 2007",
        "title_ja": "ナイロビ残骸物除去条約 (Nairobi WRC 2007)",
        "category": CAT_A,
        "legal_basis": "Nairobi WRC 2007",
        "publisher": "IMO",
        "current_edition": "2007 Edition",
        "current_edition_date": "2007-05-18",
        "update_cycle": "不定期改正",
        "priority": MANDATORY,
        "convention_trigger": "NAIROBI_WRC",
        "condition": lambda ship, conv_ids: True,  # 全船
        "applicability_rules": {
            "conventions": [],
            "ship_types": [],
            "excluded_types": [],
            "gt_min": None,
            "gt_max": None,
            "navigation": [],
            "flag_state": None,
            "class_society": None,
            "radio_equipment": [],
            "build_year_before": None,
            "build_year_after": None,
        },
        "reason_template": "全ての船舶にナイロビ残骸物除去条約の備付義務",
    },
    # 25. CTU Code
    {
        "publication_id": "CTU_CODE",
        "title": "CTU Code (IMO/ILO/UNECE Code of Practice for Packing of Cargo Transport Units)",
        "title_ja": "貨物輸送ユニット積載コード (CTU Code)",
        "category": CAT_A,
        "legal_basis": "MSC.1/Circ.1497",
        "publisher": "IMO / ILO / UNECE",
        "current_edition": "2014 Edition",
        "current_edition_date": "2014-01-01",
        "update_cycle": "不定期改正",
        "priority": RECOMMENDED,
        "convention_trigger": "SOLAS_CH_VII_DG",
        "condition": lambda ship, conv_ids: ship.get("ship_type") == "container",
        "applicability_rules": {
            "conventions": [],
            "ship_types": ["container"],
            "excluded_types": [],
            "gt_min": None,
            "gt_max": None,
            "navigation": [],
            "flag_state": None,
            "class_society": None,
            "radio_equipment": [],
            "build_year_before": None,
            "build_year_after": None,
        },
        "reason_template": "コンテナ船としてCTUコードの備付推奨",
    },
    # 26. NOx Technical Code
    {
        "publication_id": "NOX_TECHNICAL_CODE",
        "title": "NOx Technical Code 2008",
        "title_ja": "NOx技術コード 2008",
        "category": CAT_A,
        "legal_basis": "MARPOL Annex VI, Reg. 13",
        "publisher": "IMO",
        "current_edition": "2008 Edition (with amendments)",
        "current_edition_date": "2008-10-01",
        "update_cycle": "不定期改正",
        "priority": MANDATORY,
        "convention_trigger": "NOX_TECHNICAL_CODE",
        "condition": lambda ship, conv_ids: (
            "NOX_TECHNICAL_CODE" in conv_ids
            or "MARPOL_ANNEX_VI_AIR" in conv_ids
        ),
        "applicability_rules": {
            "conventions": ["NOX_TECHNICAL_CODE", "MARPOL_ANNEX_VI_AIR"],
            "ship_types": [],
            "excluded_types": [],
            "gt_min": None,
            "gt_max": None,
            "navigation": [],
            "flag_state": None,
            "class_society": None,
            "radio_equipment": [],
            "build_year_before": None,
            "build_year_after": None,
        },
        "reason_template": "MARPOL Annex VI適用船舶にNOx技術コードの備付義務",
    },
    # 27. IMSBC Code
    {
        "publication_id": "IMSBC_CODE",
        "title": "IMSBC Code (International Maritime Solid Bulk Cargoes Code)",
        "title_ja": "国際海上固体ばら積貨物コード (IMSBC Code)",
        "category": CAT_A,
        "legal_basis": "SOLAS Chapter VI, Part B",
        "publisher": "IMO",
        "current_edition": "2023 Edition (Amendment 07-23)",
        "current_edition_date": "2023-12-01",
        "update_cycle": "2年ごと改正",
        "priority": MANDATORY,
        "convention_trigger": "IMSBC_CODE",
        "condition": lambda ship, conv_ids: (
            "IMSBC_CODE" in conv_ids
            or ship.get("ship_type") in ["bulk_carrier", "general_cargo"]
        ),
        "applicability_rules": {
            "conventions": ["IMSBC_CODE"],
            "ship_types": ["bulk_carrier", "general_cargo"],
            "excluded_types": [],
            "gt_min": None,
            "gt_max": None,
            "navigation": [],
            "flag_state": None,
            "class_society": None,
            "radio_equipment": [],
            "build_year_before": None,
            "build_year_after": None,
        },
        "reason_template": "ばら積貨物運送船としてIMSBCコードの備付義務",
    },
]
